{{- if .Values.externalSecrets.enabled }}
---
# SecretStore: AWS SSM Parameter Store 연결
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.application.name }}
    managed-by: helm
spec:
  provider:
    aws:
      service: {{ required "externalSecrets.secretStore.provider is required" .Values.externalSecrets.secretStore.provider }}
      region: {{ required "externalSecrets.secretStore.region is required" .Values.externalSecrets.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ required "externalSecrets.serviceAccount.name is required" .Values.externalSecrets.serviceAccount.name }}
---
# ExternalSecret: SSM 파라미터를 K8s Secret으로 동기화
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.externalSecret.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.application.name }}
    managed-by: helm
spec:
  refreshInterval: {{ .Values.externalSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.externalSecret.name }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
  {{- end }}
{{- end }}
